- src/Website/Client/Pages/ProductPage.razor
> That is hurting my eyes

- src/Website/Client/Pages/Home/ProductPage/ProductPage.razor
[Before](https://i.imgur.com/URK89w7.png)
[After](https://i.imgur.com/E39GRPm.png)
> Remove ugly margin

- src/Website/Client/Pages/Seller/ProductPage/Components/BasicInfoTab.razor
- src/Website/Client/Pages/Seller/ProductsPage/Components/CreateProductModal.razor
- src/Website/Client/Shared/Footer.razor
i did not change any property names or stuff because i didnt want to break anything, just strings that the user can actually see
> Changed Github to GitHub

- src/Website/Client/Pages/Seller/ProductPage/Components/BasicInfoTab.razor
- src/Website/Client/Pages/Seller/ProductsPage/Components/CreateProductModal.razor
- src/Website/Client/Shared/Footer.razor
also merged the Github to GitHub commit (you would do it anyway)
> BasicInfoTab: language corrections

- src/Website/Client/Pages/Home/ProductPage/ProductPage.razor.cs
- src/Website/Client/Pages/Seller/ProductPage/Components/TabsTab.razor
- src/Website/Client/Pages/User/CheckoutPage/CheckoutPage.razor.cs
- src/Website/Client/Pages/User/SettingsPage/Components/SellerTab.razor
Brad wants to make an announcement for when this is made, and MCrow doesn't like the fact that it doesn't auto convert and it looks ugly, (the following is my opinion) despite the fact that raw HTML shouldn't have been allowed in the first place.
Reverts UnturnedStore/UnturnedStore#20
Will be re-reverted at a later stage.
> Revert "Disable Html for markdown"

- src/Website/Client/wwwroot/css/app.css
Carousel is blocking ytb video controls
> fix carousel blocking video controls

- src/Website/Server/Controllers/ProductsController.cs
Fixes and error from https://github.com/UnturnedStore/UnturnedStore/pull/24
> Fix sellers not being able to delete customers

- src/Website/Client/Pages/Home/UserPage/UserPage.razor
- src/Website/Client/Shared/Components/Products/ProductCard.razor
Makes Product Icons not blurry.
Blurry
Not Blurry
> Fix Blurry Product Icons

- src/Website/Client/Shared/NavMenu.razor
- src/Website/Client/Shared/NavMenu.razor.css
Adds an Arrow at the top of the User dropdown menu. *See Image*
**Pros;**
Looks Neat
**Cons;**
\-
***Very Minor thing*** *So thats why I am pr master*
> Top Arrow in the User dropdown menu

- src/Database/Database.sqlproj
- src/Website/Client/Pages/Home/ProductsPage/ProductsPage.razor
- src/Website/Client/Pages/Home/ProductsPage/ProductsPage.razor.cs
Virtualize will improve the render performance by limiting the number of elements that will be rendered on the main page.
I had to replace IEnumerable<MProduct> with List<MProduct> so i can use it for the virtualize component
> Replace foreach with Virtualize

- src/Website/Client/Pages/Home/IndexPage/Index.razor
- src/Website/Client/Pages/Home/IndexPage/Index.razor.cs
This does not render all the images when the page loads it renders them when you scroll down and the product card is visible on your screen
> Use virtualize instead of foreach

- src/Website/Client/Pages/Home/IndexPage/Index.razor
- src/Website/Client/Pages/Home/IndexPage/Index.razor.cs
Reverts UnturnedStore/UnturnedStore#36
It broke the website:
Should be pushed to develop instead of master next time and tested first. If a PR is made to master for something, it better be quintuple tested.
> Revert "Use virtualize instead of foreach"

- src/Website/Client/Pages/User/MessagePage/MessagePage.razor.cs
- src/Website/Client/Shared/NavMenu.razor.cs
Read isnt Updated if the Message Contains no new Messages
Messages arent Fetched twice if you Reload the MessagesPage
> Two Minor Fixes - New Messages Icon

- src/Website/Client/Shared/NavMenu.razor.cs
Fix for the Fix that wasn't Fixed because it didn't Fix it
> Fixed getting messages twice on messages page

- src/Website/Client/Pages/Home/IndexPage/Index.razor
- src/Website/Client/Pages/User/MessagePage/MessagePage.razor.cs
- src/Website/Client/Services/MessageReadService.cs
- src/Website/Client/Shared/Components/Products/ProductItem.razor
- src/Website/Client/Shared/NavMenu.razor
- src/Website/Shared/Models/Database/MMessageRead.cs
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
*I swear there is a difference*
Also fixed it so if you delete all the replies in a message and someone posts a new reply. It will show up as a new message notification for that message
*These changes have been tested and they worked completely as expected.*
> All the Minor Fixes

- src/Website/Data/Repositories/ProductsRepository.cs
- src/Website/Server/Controllers/ProductsController.cs
Yeah I missed a few things. Oops, will try to make this not happen again. Sorry :(
> Fixed a bunch of issues related to my previous Pull Request

- src/Website/Client/Pages/Home/ProductPage/Components/ProductReviewReply.razor
- src/Website/Client/Pages/Home/ProductPage/Components/ProductReviewReplyModal.razor
- src/Website/Client/wwwroot/css/app.css
- src/Website/Data/Repositories/MessagesRepository.cs
* Fixed GetNewMessages Query
* Changed the Reply's Arrow to a Line
* ![OldVsNew](https://cdn.discordapp.com/attachments/574590457128943656/1045698952223260693/image.png)
> Fixes and Changes for my previous Pull Request

- src/Website/Client/Helpers/SearchHelper.cs
- src/Website/Client/Pages/Home/ProductPage/Components/ProductReviewReply.razor
- src/Website/Client/Pages/Home/ProductPage/Components/ProductReviewReplyModal.razor
- src/Website/Client/Pages/Home/ProductPage/Components/ReviewsTab.razor
- src/Website/Client/Pages/Home/ProductPage/Components/VersionsPage.razor
- src/Website/Client/Pages/Home/ProductsPage/ProductsPage.razor
- src/Website/Client/Pages/Home/ProductsPage/ProductsPage.razor.cs
- src/Website/Client/Pages/Home/ProductsPage/ProductsPage.razor.css
- src/Website/Client/Pages/User/MessagePage/MessagePage.razor
- src/Website/Client/Shared/Components/Products/ProductCard.razor
- src/Website/Client/Shared/Components/Products/ProductWorkshopItemCard.razor
- src/Website/Components/Basic/HoverableDateTime.razor
- src/Website/Data/Repositories/BranchesRepository.cs
- src/Website/Data/Repositories/VersionsRepository.cs
- src/Website/Server/Controllers/VersionsController.cs
Fuzzy search makes finding what you're looking for way easier. Allowing for spelling mistakes or matching plugins with roughly the same name. Results from fuzzy searching are ordered based on how close they are to the original search term making it faster to find exactly what youre looking for. All this completely toggleable by the user with the click of a button.
**Implementation**
1. Get the Input and the Target
2. Split the Target into its subnames (Most if not all products are a combination of subnames)
3. Compare the first letter in each Target to the Input. If a match is found move to step 4
4. Truncate the words so that they are the same length
5. Get the string distance and compare that to the Sensitivity
DetermineSensitivity returns 0 if the Length is 3 or less meaning 0 …
> Fuzzy Search and More!

- src/Website/Client/Pages/Seller/ProductPage/Components/UploadVersion/Modals/PluginUploadModal.razor.cs
- src/Website/Data/Repositories/ProductsRepository.cs
The flag "Is Enabled" affect to the product page
> Fixed receiving the product tabs on client side

- src/Website/Client/Pages/Home/AboutPage/AboutPage.razor
merge this, has changes to the faq
> patch to faq.

- src/Website/Client/Pages/Seller/CustomersPage/Components/DetailsCustomerModal.razor
- src/Website/Client/Pages/Seller/CustomersPage/Components/DetailsCustomerModal.razor.cs
- src/Website/Client/Pages/Seller/CustomersPage/CustomersPage.razor
- src/Website/Components/DataTable/DataTable.razor
- src/Website/Components/DataTable/DataTable.razor.Grid.cs
- src/Website/Components/DataTable/DataTable.razor.cs
- src/Website/Data/Extensions/IServiceCollectionExtensions.cs
- src/Website/Data/Repositories/CustomersRepository.cs
- src/Website/Server/Controllers/CustomersController.cs
- src/Website/Server/Controllers/ProductsController.cs
Overall improve the Customers page
> Add servers information to customer details modal

- src/Website/Client/Pages/Home/ProductPage/ProductPage.razor.cs
- src/Website/Components/Helpers/MarkdownHelper.cs
- src/Website/Components/Website.Components.csproj
- src/Website/Server/Website.Server.csproj
https://github.com/UnturnedStore/UnturnedStore/pull/84
> Add HtmlSanitizer

- src/Website/Components/Helpers/MarkdownHelper.cs
sorry I was in a hurry 🤦 my bad very bad
> enable html

- src/Website/Client/Pages/Home/AboutPage/AboutPage.razor
- src/Website/Client/Pages/User/CheckoutPage/CheckoutPage.razor
- src/Website/Client/Shared/Components/Alerts/UnturnedTrademarkAlert.razor
Added a disclaimer requested in #88 
**About page:**
**Checkout page:**
> add Unturned trademark alert

- src/Website/Client/wwwroot/aup.txt
Added static resource `aup.txt` at: https://unturnedstore.com/aup.txt
> Added aup.txt
